# **Assignment 2: Diabetes Prediction using Machine Learning**

**Part 1 — Data Preparation**

1. Load the dataset using Pandas.

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [62]:
data = pd.read_csv('/content/diabetes.csv')
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

**2.Explore the dataset:**

  *a. Shape of the dataset*

In [63]:
data.shape

(768, 9)

*b.Column names*

In [64]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

*c.Data types*

In [65]:
data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

*d.Missing values, if any*

In [66]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

*e.Basic statistical summary*

In [67]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

**3.Separate the dataset into:**

*a.   Features (X)*

*b.  Target Variable (y)*

In [68]:
X = data.drop(['Outcome'], axis =1) #input columns excluding outcome
y = data['Outcome']

In [69]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [70]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

**4. Perform a Train-Test Split**

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)

In [72]:
X_train.shape

(652, 8)

In [73]:
X_test.shape

(116, 8)

**Part 2 — Machine Learning Model**

**Logistic Regeression**

In [74]:
# Import libraries
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [75]:
logistic_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
                                max_iter = 1000,
                                random_state=42
                            ))
                            ])

**Decision Tree Classifier**

In [76]:
from sklearn.tree import DecisionTreeClassifier

decison_tree_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("classifier", DecisionTreeClassifier(
        max_depth = 5,
        random_state=42
    ))
])

**Random Forest Classifier**

In [77]:
from sklearn.ensemble import RandomForestClassifier

random_forest_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("classifier", RandomForestClassifier(
        n_estimators = 200,
        max_depth=8,
        random_state=42
    ))
])

**Train all the models**

In [78]:
models = {
    "Logestic Regression" : logistic_model,
    "Decision Tree": decison_tree_model,
    "Random Forest": random_forest_model
}

for name, model in models.items():
  model.fit(X_train, y_train)
  print(f"{name} trained successfully.")

Logestic Regression trained successfully.
Decision Tree trained successfully.
Random Forest trained successfully.

**Generate Predictions**

In [79]:
predictions = {}
for name, model in models.items():
  predictions[name] = model.predict(X_test)

**Evaluvate Different Models**

In [80]:
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score )


results =[]
for name, model in models.items():
  y_pred = model.predict(X_test)

  accuracy = accuracy_score(y_test,y_pred)
  precision = precision_score(y_test, y_pred)
  recall = recall_score(y_test, y_pred)
  f1 = f1_score(y_test,y_pred)

  results.append({
      "Model":name,
      "Accuracy":accuracy,
      "Precision":precision,
      "Recall":recall,
      "F1-Score":f1
  })


results_df = pd.DataFrame(results)
print(results_df)

                 Model  Accuracy  Precision    Recall  F1-Score
0  Logestic Regression  0.818966   0.738095  0.756098  0.746988
1        Decision Tree  0.801724   0.687500  0.804878  0.741573
2        Random Forest  0.827586   0.733333  0.804878  0.767442

# **From this Random Forest is the Best model**

**Part 3 — Model Training**

 ***Fit the selected model using the training dataset.***

In [81]:
random_forest_model.fit(X_train, y_train)
print(f"Random forest model trained successfully.")

Random forest model trained successfully.

***Generate predictions on the training dataset***

In [82]:
y_train_pred = random_forest_model.predict(X_train)
print("First 10 Training Predictions")
print(y_train[:10])

First 10 Training Predictions
340    0
689    1
312    1
151    0
400    1
268    0
220    1
556    0
330    0
597    0
Name: Outcome, dtype: int64

***Evaluate the model's training performance.***

In [83]:
accuracy = accuracy_score(y_train,y_train_pred)
precision = precision_score(y_train, y_train_pred)
recall = recall_score(y_train, y_train_pred)
f1 = f1_score(y_train,y_train_pred)

print("Training data Performance")
print(f"Accuracy : {accuracy}")
print(f"Precision : {precision}")
print(f"Recall : {recall}")
print(f"F1-Score : {f1}")

Training data Performance
Accuracy : 0.9677914110429447
Precision : 0.9858490566037735
Recall : 0.920704845814978
F1-Score : 0.9521640091116174

***Generate predictions on the Test dataset and Evaluating the Performance***

In [84]:
y_test_pred = random_forest_model.predict(X_test)
accuracy_test = accuracy_score(y_test,y_test_pred)
precision_test = precision_score(y_test, y_test_pred)
recall_test = recall_score(y_test, y_test_pred)
f1_test = f1_score(y_test,y_test_pred)

print("Test data Performance")
print(f"Accuracy : {accuracy_test}")
print(f"Precision : {precision_test}")
print(f"Recall : {recall_test}")
print(f"F1-Score : {f1_test}")

Test data Performance
Accuracy : 0.8275862068965517
Precision : 0.7333333333333333
Recall : 0.8048780487804879
F1-Score : 0.7674418604651163

***Check for potential overfitting or underfitting by comparing training and testing performance.***

**Comparison Table**

In [85]:
performance_comparsion = pd.DataFrame({
    "Metric" : [
    "Accuracy",
    "Precision",
    "Recall",
    "F1-Score"
    ],
    "Training":[
        accuracy,
        precision,
        recall,
        f1
    ],
    "Testing":[
      accuracy_test,
      precision_test,
      recall_test,
      f1_test
    ]

})

performance_comparsion

      Metric  Training   Testing
0   Accuracy  0.967791  0.827586
1  Precision  0.985849  0.733333
2     Recall  0.920705  0.804878
3   F1-Score  0.952164  0.767442

In [86]:
accuracy_difference = accuracy - accuracy_test
f1_difference = f1-f1_test
if accuracy > 0.90 and accuracy_difference > 0.10 :
  print("Potential overfitting")
elif accuracy<0.70 and accuracy_test <0.70:
  print("Potential underfitting")
else:
  Print("No potential Overfitting or Underfitting")

Potential overfitting

**Part 4 — Model Evaluation**

1. Generate predictions on the test dataset.
2. Evaluate the model using:
      *   Accuracy Score
      *   Precision
      *   Recall
      *   F1-Score
      *   Confusion Matrix

3. Analyze the confusion matrix and identify:
      *   True Positives  
      *    True Negatives
      *   False Positives
      *   False Negatives
4. Compare the training and testing performance of the model.

In [87]:
from sklearn.metrics import confusion_matrix
print(f"Accuracy : {accuracy_test}")
print(f"Precision : {precision_test}")
print(f"Recall : {recall_test}")
print(f"F1-Score : {f1_test}")
cm = confusion_matrix(y_test, y_test_pred)
print(f"Confusion Matrix")
print(f"-----------------")
print(cm)

Accuracy : 0.8275862068965517
Precision : 0.7333333333333333
Recall : 0.8048780487804879
F1-Score : 0.7674418604651163
Confusion Matrix
-----------------
[[63 12]
 [ 8 33]]